export const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    period: "/month",
    description: "Perfect for candidates getting started with practice interviews.",
    features: [
      "3 practice interviews per month",
      "Basic interview feedback",
      "Resume upload",
      "Career guidance (limited)",
    ],
    cta: "Get Started",
    href: "/login/candidate",
    highlighted: false,
  },
  {
    name: "Pro",
    price: "$29",
    period: "/month",
    description: "For serious job seekers who want advanced AI coaching.",
    features: [
      "Unlimited practice interviews",
      "Advanced role-based interviews",
      "Detailed AI scoring & feedback",
      "Personalized learning recommendations",
      "Full career guidance chatbot",
    ],
    cta: "Start Pro Trial",
    href: "/login/candidate",
    highlighted: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "For HR teams hiring at scale with AI-powered screening.",
    features: [
      "Unlimited job postings",
      "AI resume matching",
      "Automated AI interviews",
      "Applicant dashboard & shortlisting",
      "Priority support",
    ],
    cta: "Contact Sales",
    href: "/contact",
    highlighted: false,
  },
];
